var e = require("../siteinfo.js"), r = "", t = {
    index: (r = -1 != e.acid ? r = e.siteroot.substr(0, e.siteroot.indexOf("app/index.php")) + "addons/zjhj_mall/core/web/index.php?_acid=" + e.acid + "&r=api/" : e.apiroot) + "default/index",
    default: {
        store: r + "default/store",
        index: r + "default/index",
        goods_list: r + "default/goods-list",
        cat_list: r + "default/cat-list",
        goods: r + "default/goods",
        district: r + "default/district",
        goods_attr_info: r + "default/goods-attr-info",
        upload_image: r + "default/upload-image",
        comment_list: r + "default/comment-list",
        article_list: r + "default/article-list",
        article_detail: r + "default/article-detail",
        video_list: r + "default/video-list",
        goods_qrcode: r + "default/goods-qrcode",
        coupon_list: r + "default/coupon-list",
        topic_list: r + "default/topic-list",
        topic: r + "default/topic",
        navbar: r + "default/navbar",
        navigation_bar_color: r + "default/navigation-bar-color",
        shop_list: r + "default/shop-list",
        shop_detail: r + "default/shop-detail",
        topic_type: r + "default/topic-type",
        buy_data: r + "default/buy-data",
        goods_recommend: r + "default/goods-recommend",
        search: r + "default/search",
        cats: r + "default/cats",
        topic_qrcode: r + "default/topic-qrcode",
        form_id: r + "default/form-id"
    },
    cart: {
        list: r + "cart/list",
        add_cart: r + "cart/add-cart",
        delete: r + "cart/delete",
        cart_edit: r + "cart/cart-edit"
    },
    passport: {
        login: r + "passport/login",
        on_login: r + "passport/on-login"
    },
    order: {
        submit_preview: r + "order/submit-preview",
        submit: r + "order/submit",
        pay_data: r + "order/pay-data",
        list: r + "order/list",
        revoke: r + "order/revoke",
        confirm: r + "order/confirm",
        count_data: r + "order/count-data",
        detail: r + "order/detail",
        refund_preview: r + "order/refund-preview",
        refund: r + "order/refund",
        refund_detail: r + "order/refund-detail",
        comment_preview: r + "order/comment-preview",
        comment: r + "order/comment",
        express_detail: r + "order/express-detail",
        clerk: r + "order/clerk",
        clerk_detail: r + "order/clerk-detail",
        get_qrcode: r + "order/get-qrcode",
        location: r + "order/location",
        refund_send: r + "order/refund-send",
        new_submit_preview: r + "order/new-submit-preview",
        new_submit: r + "order/new-submit"
    },
    user: {
        address_list: r + "user/address-list",
        address_detail: r + "user/address-detail",
        address_save: r + "user/address-save",
        address_set_default: r + "user/address-set-default",
        address_delete: r + "user/address-delete",
        save_form_id: r + "user/save-form-id",
        favorite_add: r + "user/favorite-add",
        favorite_remove: r + "user/favorite-remove",
        favorite_list: r + "user/favorite-list",
        index: r + "user/index",
        wechat_district: r + "user/wechat-district",
        add_wechat_address: r + "user/add-wechat-address",
        topic_favorite: r + "user/topic-favorite",
        topic_favorite_list: r + "user/topic-favorite-list",
        member: r + "user/member",
        card: r + "user/card",
        card_qrcode: r + "user/card-qrcode",
        card_clerk: r + "user/card-clerk",
        web_login: r + "user/web-login",
        submit_member: r + "user/submit-member",
        user_binding: r + "user/user-binding",
        user_hand_binding: r + "user/user-hand-binding",
        user_empower: r + "user/user-empower",
        sms_setting: r + "user/sms-setting",
        authorization_bind: r + "user/authorization-bind",
        check_bind: r + "user/check-bind",
        card_detail: r + "user/card-detail"
    },
    share: {
        join: r + "share/join",
        check: r + "share/check",
        get_info: r + "share/get-info",
        get_price: r + "share/get-price",
        apply: r + "share/apply",
        cash_detail: r + "share/cash-detail",
        get_qrcode: r + "share/get-qrcode",
        shop_share: r + "share/shop-share",
        bind_parent: r + "share/bind-parent",
        get_team: r + "share/get-team",
        get_order: r + "share/get-order",
        index: r + "share/index"
    },
    coupon: {
        index: r + "coupon/index",
        share_send: r + "coupon/share-send",
        receive: r + "coupon/receive",
        coupon_detail: r + "coupon/detail"
    },
    miaosha: {
        list: r + "miaosha/list",
        goods_list: r + "miaosha/goods-list",
        details: r + "miaosha/details",
        submit_preview: r + "miaosha/submit-preview",
        submit: r + "miaosha/submit",
        pay_data: r + "miaosha/pay-data",
        order_list: r + "miaosha/order-list",
        order_details: r + "miaosha/order-details",
        order_revoke: r + "miaosha/revoke",
        express_detail: r + "miaosha/express-detail",
        confirm: r + "miaosha/confirm",
        comment_preview: r + "miaosha/comment-preview",
        comment: r + "miaosha/comment",
        refund_preview: r + "miaosha/refund-preview",
        refund: r + "miaosha/refund",
        refund_detail: r + "miaosha/refund-detail",
        comment_list: r + "miaosha/comment-list",
        goods_qrcode: r + "miaosha/goods-qrcode"
    },
    group: {
        index: r + "group/index/index",
        list: r + "group/index/good-list",
        details: r + "group/index/good-details",
        goods_attr_info: r + "group/index/goods-attr-info",
        submit_preview: r + "group/order/submit-preview",
        submit: r + "group/order/submit",
        pay_data: r + "group/order/pay-data",
        order: {
            list: r + "group/order/list",
            detail: r + "group/order/detail",
            express_detail: r + "group/order/express-detail",
            comment_preview: r + "group/order/comment-preview",
            comment: r + "group/order/comment",
            confirm: r + "group/order/confirm",
            goods_qrcode: r + "group/order/goods-qrcode",
            get_qrcode: r + "group/order/get-qrcode",
            clerk: r + "group/order/clerk",
            clerk_order_details: r + "group/order/clerk-order-details",
            revoke: r + "group/order/revoke",
            refund_preview: r + "group/order/refund-preview",
            refund: r + "group/order/refund",
            refund_detail: r + "group/order/refund-detail"
        },
        group_info: r + "group/order/group",
        comment: r + "group/index/goods-comment",
        goods_qrcode: r + "group/index/goods-qrcode",
        search: r + "group/index/search"
    },
    book: {
        index: r + "book/index/index",
        list: r + "book/index/good-list",
        details: r + "book/index/good-details",
        submit_preview: r + "book/order/submit-preview",
        submit: r + "book/order/submit",
        order_list: r + "book/order/list",
        order_cancel: r + "book/order/cancel",
        order_pay: r + "book/order/pay-data",
        order_details: r + "book/order/order-details",
        shop_list: r + "book/index/shop-list",
        get_qrcode: r + "book/order/get-qrcode",
        clerk: r + "book/order/clerk",
        apply_refund: r + "book/order/apply-refund",
        comment_preview: r + "book/order/comment-preview",
        submit_comment: r + "book/order/comment",
        goods_comment: r + "book/index/goods-comment",
        goods_qrcode: r + "book/index/goods-qrcode",
        clerk_order_details: r + "book/order/clerk-order-details",
        goods_attr_info: r + "book/index/goods-attr-info"
    },
    quick: {
        quick: r + "quick/quick/quick",
        quick_goods: r + "quick/quick/quick-goods",
        quick_car: r + "quick/quick/quick-car"
    },
    fxhb: {
        open: r + "fxhb/index/open",
        open_submit: r + "fxhb/index/open-submit",
        detail: r + "fxhb/index/detail",
        detail_submit: r + "fxhb/index/detail-submit"
    },
    recharge: {
        index: r + "recharge/index",
        list: r + "recharge/list",
        submit: r + "recharge/submit",
        record: r + "recharge/record",
        detail: r + "recharge/detail"
    },
    mch: {
        apply: r + "mch/index/apply",
        apply_submit: r + "mch/index/apply-submit",
        shop: r + "mch/index/shop",
        shop_list: r + "mch/index/shop-list",
        shop_cat: r + "mch/index/shop-cat",
        user: {
            myshop: r + "mch/user/myshop",
            setting: r + "mch/user/setting",
            setting_submit: r + "mch/user/setting-submit",
            shop_qrcode: r + "mch/user/shop-qrcode",
            account: r + "mch/user/account",
            cash: r + "mch/user/cash",
            account_log: r + "mch/user/account-log",
            cash_log: r + "mch/user/cash-log",
            tongji_year_list: r + "mch/user/tongji-year-list",
            tongji_month_data: r + "mch/user/tongji-month-data",
            cash_preview: r + "mch/user/cash-preview",
            settle_log: r + "mch/user/settle-log"
        },
        goods: {
            list: r + "mch/goods/list",
            set_status: r + "mch/goods/set-status",
            delete: r + "mch/goods/delete"
        },
        order: {
            list: r + "mch/order/list",
            detail: r + "mch/order/detail",
            send: r + "mch/order/send",
            refund: r + "mch/order/refund",
            edit_price: r + "mch/order/edit-price",
            refund_detail: r + "mch/order/refund-detail"
        }
    },
    integral: {
        index: r + "integralmall/integralmall/index",
        coupon_info: r + "integralmall/integralmall/coupon-info",
        exchange_coupon: r + "integralmall/integralmall/exchange-coupon",
        integral_pay: r + "integralmall/integralmall/integral-pay",
        goods_info: r + "integralmall/integralmall/goods-info",
        submit_preview: r + "integralmall/integralmall/submit-preview",
        submit: r + "integralmall/integralmall/submit",
        list: r + "integralmall/integralmall/list",
        revoke: r + "integralmall/integralmall/revoke",
        order_submit: r + "integralmall/integralmall/order-submit",
        confirm: r + "integralmall/integralmall/confirm",
        get_qrcode: r + "integralmall/integralmall/get-qrcode",
        clerk_order_details: r + "integralmall/integralmall/clerk-order-details",
        clerk: r + "integralmall/integralmall/clerk",
        explain: r + "integralmall/integralmall/explain",
        exchange: r + "integralmall/integralmall/exchange",
        register: r + "integralmall/integralmall/register",
        integral_detail: r + "integralmall/integralmall/integral-detail",
        goods_list: r + "integralmall/integralmall/goods-list"
    },
    pond: {
        index: r + "pond/pond/index",
        lottery: r + "pond/pond/lottery",
        prize: r + "pond/pond/prize",
        send: r + "pond/pond/send",
        setting: r + "pond/pond/setting",
        submit: r + "pond/pond/submit",
        qrcode: r + "pond/pond/qrcode"
    },
    bargain: {
        index: r + "bargain/default/index",
        goods: r + "bargain/default/goods",
        bargain_submit: r + "bargain/order/bargain-submit",
        activity: r + "bargain/order/activity",
        bargain: r + "bargain/order/bargain",
        order_list: r + "bargain/order/order-list",
        setting: r + "bargain/default/setting",
        goods_user: r + "bargain/default/goods-user",
        qrcode: r + "bargain/default/qrcode"
    },
    scratch: {
        index: r + "scratch/scratch/index",
        receive: r + "scratch/scratch/receive",
        setting: r + "scratch/scratch/setting",
        prize: r + "scratch/scratch/prize",
        submit: r + "scratch/scratch/submit",
        log: r + "scratch/scratch/log",
        qrcode: r + "scratch/scratch/qrcode"
    },
    lottery: {
        index: r + "lottery/default/index",
        prize: r + "lottery/default/prize",
        detail: r + "lottery/default/detail",
        goods: r + "lottery/default/goods",
        submit: r + "lottery/default/submit",
        qrcode: r + "lottery/default/qrcode",
        setting: r + "lottery/default/setting",
        lucky_code: r + "lottery/default/lucky-code",
        clerk: r + "lottery/default/clerk"
    },
    step: {
        index: r + "step/default/index",
        setting: r + "step/default/setting",
        qrcode: r + "step/default/qrcode",
        log: r + "step/default/log",
        convert: r + "step/default/convert",
        ranking: r + "step/default/ranking",
        goods: r + "step/default/goods",
        activity: r + "step/default/activity",
        activity_join: r + "step/default/activity-join",
        activity_detail: r + "step/default/activity-detail",
        submit: r + "step/default/submit",
        activity_log: r + "step/default/activity-log",
        activity_submit: r + "step/default/activity-submit",
        remind: r + "step/default/remind",
        pic_list: r + "step/default/pic-list",
        invite_detail: r + "step/default/invite-detail"
    }
};

module.exports = t;