function _(_, T, I) {
    return T in _ ? Object.defineProperty(_, T, {
        value: I,
        enumerable: !0,
        configurable: !0,
        writable: !0
    }) : _[T] = I, _;
}

var T;

module.exports = (T = {
    FORM_ID_LIST: "FORM_ID_LIST",
    LOGIN_PRE_PAGE: "LOGIN_PRE_PAGE",
    NAVIGATION_BAR_COLOR: "NAVIGATION_BAR_COLOR",
    WX_BAR_TITLE: "WX_BAR_TITLE",
    USER_INFO: "USER_INFO",
    STORE_CONFIG: "STORE_CONFIG",
    STORE: "STORE",
    STORE_NAME: "STORE_NAME",
    SHOW_CUSTOMER_SERVICE: "SHOW_CUSTOMER_SERVICE",
    CONTACT_TEL: "CONTACT_TEL",
    SHARE_SETTING: "SHARE_SETTING",
    WXAPP_IMG: "WXAPP_IMG"
}, _(T, "WX_BAR_TITLE", "WX_BAR_TITLE"), _(T, "ALIPAY_MP_CONFIG", "ALIPAY_MP_CONFIG"), 
_(T, "PAGE_INDEX_INDEX", "PAGE_INDEX_INDEX"), _(T, "ITEM", "ITEM"), _(T, "CAT_LIST", "CAT_LIST"), 
_(T, "LIST_PAGE_RELOAD", "LIST_PAGE_RELOAD"), _(T, "LIST_PAGE_OPTIONS", "LIST_PAGE_OPTIONS"), 
_(T, "PICKER_ADDRESS", "PICKER_ADDRESS"), _(T, "DISTRICT", "DISTRICT"), _(T, "CUSTOM", "CUSTOM"), 
_(T, "DISTRICT", "DISTRICT"), _(T, "INPUT_DATA", "INPUT_DATA"), _(T, "PAGES_USER_USER", "PAGES_USER_USER"), 
_(T, "SEARCH_HISTORY_LIST", "SEARCH_HISTORY_LIST"), _(T, "PT_GROUP_DETAIL", "PT_GROUP_DETAIL"), 
_(T, "HISTORY_INFO", "HISTORY_INFO"), _(T, "CURRENT_DAY_LIST", "CURRENT_DAY_LIST"), 
_(T, "ACCESS_TOKEN", "ACCESS_TOKEN"), _(T, "QUICK_LIST", "QUICK_LIST"), _(T, "QUICK_LISTS", "QUICK_LISTS"), 
_(T, "CARGOODS", "CARGOODS"), _(T, "TOTAL", "TOTAL"), _(T, "CHECK_NUM", "CHECK_NUM"), 
_(T, "QUICK_HOT_GOODS_LISTS", "QUICK_HOT_GOODS_LISTS"), _(T, "PARENT_ID", "PARENT_ID"), 
_(T, "NAVIGATION_BAR_COLOR", "NAVIGATION_BAR_COLOR"), T);